version: '2'

services:

  itop-app:
    container_name: itop-app
    image: vbkunin/itop:latest
    depends_on:
      - itop-db
    tty: true         # to have nice debug(...) outputs
    stdin_open: true  # to be able to use CTRL+C to stop the debug
    ports:
      - 8080:80
    restart: unless-stopped

  itop-db:
    container_name: itop-db
    image: mysql:5
    environment:
      MYSQL_DATABASE: "itop"
      MYSQL_USER: "itop"
      MYSQL_PASSWORD: "itop"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    tty: true         # to have nice debug(...) outputs
    stdin_open: true  # to be able to use CTRL+C to stop the debug
    restart: unless-stopped